export const subjects = [
  "Human Computer Interaction",
  "Computer Graphics",
  "Web Design and Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
];

export const assignments = [
  {
    title: "Usability Testing Report",
    course: "Human Computer Interaction",
    topic: "Evaluating UI/UX design",
    dueDate: "2025-03-10",
    status: "Due",
  },
  {
    title: "Heuristic Evaluation",
    course: "Human Computer Interaction",
    topic: "Nielsen's usability principles",
    dueDate: "2025-02-28",
    status: "Overdue",
  },
  {
    title: "Persona & User Journey",
    course: "Human Computer Interaction",
    topic: "Creating user personas",
    dueDate: "2025-03-15",
    status: "Submitted",
  },
  {
    title: "3D Modeling Project",
    course: "Computer Graphics",
    topic: "Blender 3D shapes",
    dueDate: "2025-03-12",
    status: "Due",
  },
  {
    title: "Ray Tracing Algorithm",
    course: "Computer Graphics",
    topic: "Light and shadow simulation",
    dueDate: "2025-02-25",
    status: "Overdue",
  },
  {
    title: "Shader Programming",
    course: "Computer Graphics",
    topic: "Writing GLSL shaders",
    dueDate: "2025-03-08",
    status: "Submitted",
  },
  {
    title: "Responsive Web Design",
    course: "Web Design and Development",
    topic: "CSS Flexbox & Grid",
    dueDate: "2025-03-05",
    status: "Due",
  },
  {
    title: "JavaScript DOM Manipulation",
    course: "Web Design and Development",
    topic: "Handling user interactions",
    dueDate: "2025-02-27",
    status: "Overdue",
  },
  {
    title: "Full-Stack Project",
    course: "Web Design and Development",
    topic: "Building a MERN app",
    dueDate: "2025-03-20",
    status: "Submitted",
  },
  {
    title: "AI Chatbot Development",
    course: "Artificial Intelligence",
    topic: "Using NLP for chatbot",
    dueDate: "2025-03-14",
    status: "Due",
  },
  {
    title: "AI Ethics Paper",
    course: "Artificial Intelligence",
    topic: "Bias in AI systems",
    dueDate: "2025-02-22",
    status: "Overdue",
  },
  {
    title: "Neural Network Implementation",
    course: "Artificial Intelligence",
    topic: "TensorFlow basics",
    dueDate: "2025-03-10",
    status: "Submitted",
  },
  {
    title: "ML Model Evaluation",
    course: "Machine Learning",
    topic: "Hyperparameter tuning",
    dueDate: "2025-03-09",
    status: "Due",
  },
  {
    title: "Regression Analysis",
    course: "Machine Learning",
    topic: "Linear regression models",
    dueDate: "2025-02-26",
    status: "Overdue",
  },
  {
    title: "Image Classification",
    course: "Machine Learning",
    topic: "CNN for object detection",
    dueDate: "2025-03-12",
    status: "Submitted",
  },
  {
    title: "Big Data Processing",
    course: "Data Science",
    topic: "Using Apache Spark",
    dueDate: "2025-03-07",
    status: "Due",
  },
  {
    title: "Data Cleaning Project",
    course: "Data Science",
    topic: "Handling missing values",
    dueDate: "2025-02-24",
    status: "Overdue",
  },
  {
    title: "Exploratory Data Analysis",
    course: "Data Science",
    topic: "Using Pandas & Matplotlib",
    dueDate: "2025-03-16",
    status: "Submitted",
  },
];

export const sampleData = {
  teacher: {
    id: "T001",
    name: "Dr. Sarah Ahmed",
    email: "sarah.ahmed@emaan.edu.pk",
    department: "Computer Science",
    photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    assignedCourses: ["CCP231", "CCP244", "CCP301"],
  },
  courses: [
    {
      code: "CCP231",
      name: "Design & Analysis of Algorithm",
      credits: 3,
      semester: "5th",
    },
    { code: "CCP244", name: "Theory of Automata", credits: 4, semester: "5th" },
    {
      code: "CCP301",
      name: "Database Management Systems",
      credits: 4,
      semester: "6th",
    },
  ],
  schedule: [
    {
      id: 1,
      courseCode: "CCP231",
      courseName: "Design & Analysis of Algorithm",
      day: "Monday",
      time: "9:00 AM - 11:00 AM",
      room: "Lab-101",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 2,
      courseCode: "CCP244",
      courseName: "Theory of Automata",
      day: "Wednesday",
      time: "9:00 AM - 11:00 AM",
      room: "Room-205",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 3,
      courseCode: "CCP231",
      courseName: "Design & Analysis of Algorithm",
      day: "Thursday",
      time: "11:00 AM - 1:00 PM",
      room: "Lab-101",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 4,
      courseCode: "CCP301",
      courseName: "Database Management Systems",
      day: "Tuesday",
      time: "2:00 PM - 4:00 PM",
      room: "Lab-303",
      semester: "6th",
      session: "Evening",
    },
    {
      id: 5,
      courseCode: "CCP244",
      courseName: "Theory of Automata",
      day: "Friday",
      time: "11:00 AM - 1:00 PM",
      room: "Room-205",
      semester: "5th",
      session: "Morning",
    },
  ],
  students: [
    {
      id: "S001",
      regNo: "BCS-M/SP-25/22",
      name: "Ali Hassan",
      semester: "5th",
      session: "Morning",
      courses: ["CCP231", "CCP244"],
    },
    {
      id: "S002",
      regNo: "BCS-M/SP-26/22",
      name: "Fatima Khan",
      semester: "5th",
      session: "Morning",
      courses: ["CCP231", "CCP244"],
    },
    {
      id: "S003",
      regNo: "BCS-M/SP-27/22",
      name: "Ahmed Malik",
      semester: "5th",
      session: "Morning",
      courses: ["CCP231", "CCP244"],
    },
    {
      id: "S004",
      regNo: "BCS-E/SP-28/22",
      name: "Ayesha Noor",
      semester: "6th",
      session: "Evening",
      courses: ["CCP301"],
    },
    {
      id: "S005",
      regNo: "BCS-E/SP-29/22",
      name: "Usman Ali",
      semester: "6th",
      session: "Evening",
      courses: ["CCP301"],
    },
  ],
  assignments: [
    {
      id: 1,
      title: "Graph Algorithms Implementation",
      courseCode: "CCP231",
      description: "Implement BFS, DFS and Dijkstra algorithm",
      dueDate: "2024-11-15",
      marks: 20,
      semester: "5th",
      session: "Morning",
      status: "active",
      submissions: 15,
    },
    {
      id: 2,
      title: "DFA and NFA Construction",
      courseCode: "CCP244",
      description: "Create DFA and NFA for given regular expressions",
      dueDate: "2024-11-20",
      marks: 15,
      semester: "5th",
      session: "Morning",
      status: "active",
      submissions: 12,
    },
    {
      id: 3,
      title: "SQL Queries and Normalization",
      courseCode: "CCP301",
      description: "Write complex SQL queries and normalize database schema",
      dueDate: "2024-11-18",
      marks: 25,
      semester: "6th",
      session: "Evening",
      status: "active",
      submissions: 8,
    },
  ],
  submissions: [
    {
      id: 1,
      studentId: "S001",
      studentName: "Ali Hassan",
      assignmentId: 1,
      submittedDate: "2024-11-10",
      file: "graph_algorithms.zip",
      marks: 18,
      totalMarks: 20,
      status: "graded",
    },
    {
      id: 2,
      studentId: "S002",
      studentName: "Fatima Khan",
      assignmentId: 1,
      submittedDate: "2024-11-11",
      file: "graph_impl.zip",
      marks: null,
      totalMarks: 20,
      status: "pending",
    },
    {
      id: 3,
      studentId: "S003",
      studentName: "Ahmed Malik",
      assignmentId: 2,
      submittedDate: "2024-11-12",
      file: "automata.pdf",
      marks: 14,
      totalMarks: 15,
      status: "graded",
    },
  ],
  lectures: [
    {
      id: 1,
      topic: "Introduction to Graph Theory",
      courseCode: "CCP231",
      class: 1,
      file: "graph_theory.pdf",
      uploadDate: "2024-10-15",
    },
    {
      id: 2,
      topic: "Sorting Algorithms",
      courseCode: "CCP231",
      class: 3,
      file: "sorting.pdf",
      uploadDate: "2024-10-22",
    },
    {
      id: 3,
      topic: "Regular Expressions",
      courseCode: "CCP244",
      class: 2,
      file: "regex.pdf",
      uploadDate: "2024-10-18",
    },
    {
      id: 4,
      topic: "SQL Basics",
      courseCode: "CCP301",
      class: 1,
      file: "sql_basics.pdf",
      uploadDate: "2024-10-20",
    },
  ],
  attendance: [
    {
      id: 1,
      studentId: "S001",
      studentName: "Ali Hassan",
      date: "2024-10-25",
      courseCode: "CCP231",
      status: "present",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 2,
      studentId: "S002",
      studentName: "Fatima Khan",
      date: "2024-10-25",
      courseCode: "CCP231",
      status: "present",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 3,
      studentId: "S003",
      studentName: "Ahmed Malik",
      date: "2024-10-25",
      courseCode: "CCP231",
      status: "absent",
      semester: "5th",
      session: "Morning",
    },
    {
      id: 4,
      studentId: "S001",
      studentName: "Ali Hassan",
      date: "2024-10-25",
      courseCode: "CCP244",
      status: "present",
      semester: "5th",
      session: "Morning",
    },
  ],
};
